name: Auto Merge and Notify

on:
  push:
    branches:
      - master

jobs:
  merge_and_notify:
    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: test_branch_name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge changes
        run: |
          git fetch origin
          git checkout $TARGET_BRANCH
          git pull origin $TARGET_BRANCH
          git merge ${{ github.ref }}
          git push origin $TARGET_BRANCH || { echo "Merge failed"; exit 1; }

      - name: Send Slack notification on failure
        if: failure()
        uses: slack/send-message-action@v2
        with:
          channel: your_slack_channel
          text: "Failed to merge branch '${{ github.ref }}' into $TARGET_BRANCH"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
